//
//  String.swift
//  FoodSwift
//
//  Created by Thanh Lâm on 15/10/24.
//

import Foundation

extension AppFood {
    struct String {
        // MARK: - Common
        static let welcome = "Welcome"
        static let titleWelcome = "Tamang\nFoodService"
        static let contentWelcome = "It’s a pleasure to meet you. We are excited that you’re here so let’s get started!"
        static let orangeTitleButtonWelcome = "GET STARTED"
        static let alertFailedAPI = "Failed"
        static let alertFailedToConnectAPI = "Connect Failed"
        static let alertFailedToDataAPI = "Data Covernt To Failed"
        static let connectAPI = "Connect API"
        static let alertAction = "Connect"
        static let loadSuccess = "Loading Success"
        static let haveItem = "Item is Favorites"
        static let notHaveItem = "Item not is Favorites"
        static let addObjectSuccess = "Success To Add Object"
        static let addObjectFailed = "Failed To Add Object"
        static let deleteObjectSuccess = "Success To Delete Object"
        static let deleteObjectFailed = "Failed To Delete Object"
        static let fetchData = "Fetch Data Success"
        static let failedFetchData = "Failed Fetch Data"
        static let Source = "No Has Source"
        static let okString = "OK"
        static let cancelString = "Cancel"
        static let titleAddInstructions = "Add Special Instructions"
        static let messageAddInstructions = "Add Info Meal Do You Want More Here"
        static let createAccount = "Create Account"
        static let continueAction = "Continue To Setup"
        static let collectionDBOrder = "orderMeal"
        static let collectionDBHistoryOrder = "HistoryOrderMeal"
        static let collectionDBAccount = "account"
        static let homeFeaturedPartnersString = "Featured\nPartners"
        static let titleFeaturePartners = "Feature Partners"
        static let seeAllString = "See all"
        static let famousResFoodTitle = "Best Picks\nRestaurants by\nteam"
        static let titleNationMeal = "National Specialties"
        static let allRestaurantsTitle = "All Restaurants"
        static let deliveryString = "DELIVERY TO"
        static let filterString = "Filter"
        static let titleDetailFeaturedItem = "Featured Items"
        static let freeString = "Free"
        static let deliveryDetailString = "Delivery"
        static let dollarsString = "Dollars"
        static let minutesString = "Minutes"
        static let titleTakeAwayButton = "TAKE AWAY"
        static let freeDeliveryString = "Free delivery"
        static let subTotalString = "Subtotal"
        static let addMoreItemString = "Add more items"
        static let promoCodeString = "Promo Code"
        static let yourOrderTitle = "Your Orders"
        static let addYourPaymentMethod = "Add your payment methods"
        static let subjectMethodsPayment = "This card will only be charged when\n you place an order."
        static let addCardTitleButton = "ADD CARD"
        static let scanCardTitleButton = "SCAN CARD"
        static let searchTitle = "Search"
        static let placeHolderSearchTextField = "Search on foodly"
        static let nationString = "Nation"
        static let categoryString = "Category"
        static let enterYourMealSearchString = "Enter Your Name Meal For Search..."
        static let clearAllButtonTitle = "Clear All"
    }
    
    struct StringImage {
        static let iconTamago = "icon-tamago"
        static let welcomeImage = "Welcome-image"
        static let logoTamago = "logo_tamano"
        static let starIcon = "Star"
        static let timberIcon = "detail_timer"
        static let dollarIcon = "Dollar"
        static let backDownIcon = "back_down"
        static let fastClockIcon = "fast-clock"
        static let feeShipIcon = "fee_ship"
        static let bannerIcon = "Banner"
        static let whiteBackIcon = "white_back"
        static let combinedShapeIcon = "Combined_Shape"
        static let whiteSearchIcon = "white_search"
        static let activeIcon = "active"
        static let dollarIconDetail = "dollar"
        static let blackCloseIcon = "black_close"
        static let leftArrowBackIcon = "left_arrow_back"
        static let cameraIcon = "camera"
        static let searchIcon = "search"
        static let emptySearchImage = "search_waste_food"
        static let backButton = "back"
    }
}
